apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:
    grafana
  labels:
    task: monitoring
  namespace: infrastructure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: docker.io/grafana/grafana:5.2.4
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 30