apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: infrastructure
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocal: TCP
  selector:
    app: grafana